//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignature
    {
        public Asignature()
        {
            this.CourseAsignatures = new HashSet<CourseAsignature>();
        }
    
        public int id { get; set; }
        public int idAreaConocimiento { get; set; }
        public int idGrado { get; set; }
        public string Descripcion { get; set; }
        public int intensidadHoraria { get; set; }
        public Nullable<bool> ignorarEnPromedio { get; set; }
        public Nullable<decimal> pesoPorcentualAreaConocimiento { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual KnowledgeArea KnowledgeArea { get; set; }
        public virtual ICollection<CourseAsignature> CourseAsignatures { get; set; }
    }
}
