//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseStudents = new HashSet<CourseStudent>();
            this.CourseAsignatures = new HashSet<CourseAsignature>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public int idJornada { get; set; }
        public int idSede { get; set; }
        public int idGrado { get; set; }
        public int ano { get; set; }
        public string Descripcion { get; set; }
        public int idDirectorCurso { get; set; }
        public bool finalizado { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Place Place { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
        public virtual ICollection<CourseAsignature> CourseAsignatures { get; set; }
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
    }
}
