//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseAsignatures = new HashSet<CourseAsignature>();
            this.CourseStudents = new HashSet<CourseStudent>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public int idJornada { get; set; }
        public int idSede { get; set; }
        public int idGrado { get; set; }
        public int ano { get; set; }
        public string Descripcion { get; set; }
        public int idDirectorCurso { get; set; }
        public bool finalizado { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Place Place { get; set; }
        public virtual ICollection<CourseAsignature> CourseAsignatures { get; set; }
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
    }
}
