//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationNote
    {
        public EvaluationNote()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.Evaluations1 = new HashSet<Evaluation>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public string Comentario { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Evaluation> Evaluations1 { get; set; }
        public virtual School School { get; set; }
    }
}
