//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Courses = new HashSet<Course>();
            this.Asignatures = new HashSet<Asignature>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public string NombreGrado { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Asignature> Asignatures { get; set; }
        public virtual School School { get; set; }
    }
}
