//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeArea
    {
        public KnowledgeArea()
        {
            this.Asignatures = new HashSet<Asignature>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public string descripcion { get; set; }
        public int posicionBoletin { get; set; }
    
        public virtual ICollection<Asignature> Asignatures { get; set; }
        public virtual School School { get; set; }
    }
}
