//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAttachment
    {
        public int id { get; set; }
        public int idNoticia { get; set; }
        public string rutaAdjunto { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
    }
}
