//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPaper
    {
        public NewsPaper()
        {
            this.NewsAttachments = new HashSet<NewsAttachment>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public System.DateTime fecha { get; set; }
        public string titulo { get; set; }
        public string noticia { get; set; }
    
        public virtual ICollection<NewsAttachment> NewsAttachments { get; set; }
        public virtual School School { get; set; }
    }
}
