//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAttachment
    {
        public int id { get; set; }
        public int idNoticia { get; set; }
        public string rutaAdjunto { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
    }
}
