//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPaper
    {
        public NewsPaper()
        {
            this.NewsAttachments = new HashSet<NewsAttachment>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public System.DateTime fecha { get; set; }
        public string titulo { get; set; }
        public string noticia { get; set; }
    
        public virtual ICollection<NewsAttachment> NewsAttachments { get; set; }
        public virtual School School { get; set; }
    }
}
