//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.CourseAsignatures = new HashSet<CourseAsignature>();
            this.CourseStudents = new HashSet<CourseStudent>();
            this.PersonBitacores = new HashSet<PersonBitacore>();
            this.Courses = new HashSet<Course>();
            this.StudentLogs = new HashSet<StudentLog>();
            this.StudentLogs1 = new HashSet<StudentLog>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public int idSede { get; set; }
        public int idJornada { get; set; }
        public int idRol { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public bool usuarioActivo { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string tipoDocumento { get; set; }
        public string documento { get; set; }
        public bool sexo { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string padre { get; set; }
        public string telefonoPadre { get; set; }
        public string madre { get; set; }
        public string telefonoMadre { get; set; }
        public string nombreOtroContacto { get; set; }
        public string telefonoOtroContacto { get; set; }
        public bool retirado { get; set; }
    
        public virtual ICollection<CourseAsignature> CourseAsignatures { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
        public virtual Place Place { get; set; }
        public virtual ICollection<PersonBitacore> PersonBitacores { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<StudentLog> StudentLogs { get; set; }
        public virtual ICollection<StudentLog> StudentLogs1 { get; set; }
        public virtual School School { get; set; }
    }
}
