//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Courses = new HashSet<Course>();
            this.People = new HashSet<Person>();
        }
    
        public int id { get; set; }
        public int idColegio { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual School School { get; set; }
    }
}
