//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.AcademicPeriods = new HashSet<AcademicPeriod>();
            this.Courses = new HashSet<Course>();
            this.EvaluationNotes = new HashSet<EvaluationNote>();
            this.Grades = new HashSet<Grade>();
            this.KnowledgeAreas = new HashSet<KnowledgeArea>();
            this.NewsPapers = new HashSet<NewsPaper>();
            this.People = new HashSet<Person>();
            this.Places = new HashSet<Place>();
            this.ValuationLevels = new HashSet<ValuationLevel>();
        }
    
        public int id { get; set; }
        public string nombreColegio { get; set; }
        public string nit { get; set; }
        public string especialidad { get; set; }
        public string resolucion { get; set; }
        public string registroEducativo { get; set; }
        public string registroDANE { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string departamento { get; set; }
        public string logo { get; set; }
        public string nombreRector { get; set; }
        public string nombreSecretario { get; set; }
        public string textoCertificacion { get; set; }
        public bool pesoAreaConocimiento { get; set; }
        public bool notaComportamientoLetras { get; set; }
        public bool mostrarRectorBoletin { get; set; }
    
        public virtual ICollection<AcademicPeriod> AcademicPeriods { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<EvaluationNote> EvaluationNotes { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<KnowledgeArea> KnowledgeAreas { get; set; }
        public virtual ICollection<NewsPaper> NewsPapers { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<ValuationLevel> ValuationLevels { get; set; }
    }
}
