//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAbsence
    {
        public int id { get; set; }
        public int idEstudiante { get; set; }
        public int idAsignatura { get; set; }
        public int idPeriodoAcademico { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual AcademicPeriod AcademicPeriod { get; set; }
        public virtual CourseStudent CourseStudent { get; set; }
        public virtual CourseAsignature CourseAsignature { get; set; }
    }
}
