//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskAttachments = new HashSet<TaskAttachment>();
        }
    
        public int id { get; set; }
        public int idAsignatura { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public bool activo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        public virtual CourseAsignature CourseAsignature { get; set; }
        public virtual ICollection<TaskAttachment> TaskAttachments { get; set; }
    }
}
