//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskAttachments = new HashSet<TaskAttachment>();
        }
    
        public int id { get; set; }
        public int idAsignatura { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public bool activo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        public virtual CourseAsignature CourseAsignature { get; set; }
        public virtual ICollection<TaskAttachment> TaskAttachments { get; set; }
    }
}
