//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuationLevel
    {
        public int id { get; set; }
        public int idColegio { get; set; }
        public string descripcion { get; set; }
        public decimal minimo { get; set; }
        public decimal maximo { get; set; }
        public bool noSupera { get; set; }
        public string valorLetra { get; set; }
    
        public virtual School School { get; set; }
    }
}
