//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuationLevel
    {
        public int id { get; set; }
        public int idColegio { get; set; }
        public string descripcion { get; set; }
        public decimal minimo { get; set; }
        public decimal maximo { get; set; }
        public bool noSupera { get; set; }
    
        public virtual School School { get; set; }
    }
}
