//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.SchoolPanel.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Orkidea.SchoolPanel.Entities;
    
    public partial class SchoolPanelEntities : DbContext
    {
        public SchoolPanelEntities()
            : base("name=SchoolPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicPeriod> AcademicPeriods { get; set; }
        public DbSet<CourseStudent> CourseStudents { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<KnowledgeArea> KnowledgeAreas { get; set; }
        public DbSet<NewsAttachment> NewsAttachments { get; set; }
        public DbSet<NewsPaper> NewsPapers { get; set; }
        public DbSet<PersonBitacore> PersonBitacores { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<StudentAbsence> StudentAbsences { get; set; }
        public DbSet<TaskAttachment> TaskAttachments { get; set; }
        public DbSet<CourseAsignature> CourseAsignatures { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Person> Persons { get; set; }
        public DbSet<EvaluationNote> EvaluationNotes { get; set; }
        public DbSet<ValuationLevel> ValuationLevels { get; set; }
        public DbSet<Evaluation> Evaluations { get; set; }
        public DbSet<Asignature> Asignatures { get; set; }
        public DbSet<School> Schools { get; set; }
    }
}
